FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y install --no-install-recommends \
  systemd systemd-sysv dbus ca-certificates sudo nano bash-completion \
  build-essential pkg-config cmake git curl file gdb \
  libssl-dev vim mc htop tmux \
  libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev \
  && apt-get clean

COPY ./getty-override.conf \
  /etc/systemd/system/console-getty.service.d/override.conf

RUN echo "export MAKEFLAGS=-j" >> /root/.profile

CMD ["/lib/systemd/systemd"]
