name: Code Formatting Check

on:
    push:
    workflow_dispatch:
    pull_request:

jobs:
  clang-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Check Formatting
      uses: FreeRTOS/CI-CD-Github-Actions/clang-formatting@main
      with:
        path: examples/