name: formatting
on:
    push:
    workflow_dispatch:
    pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: |
          uncrustify -c ./uncrustify.cfg --no-backup --replace examples/*/*.c examples/*/*.h
          git diff
          git diff | diff - /dev/null &> /dev/null
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep examples -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Trailing whitespace check failed."
            exit 1
          else
            exit 0
          fi
