name: formatting
on:
    push:
    workflow_dispatch:
    pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: |
          find examples -iname "*.[hc]" -exec uncrustify --check -c ./uncrustify.cfg {} +
          if [ "$?" = "0" ]; then
            exit 0
          else
            echo -e "\033[31;1;43mFormatting check (using Uncrustify) failed...\033[0m"
            exit 1
          fi
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep --exclude-dir="bla" --exclude="bla" -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi
