name: uncrustify
on:
    push:
    workflow_dispatch:
    pull_request:
jobs:
  uncrustify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache uncrustify
        uses: actions/cache@v4
        id: cache-uncrustify
        with:
          path: |
            ~/uncrustify
          key: ${{ runner.os }}-uncrustify
      - name: build uncrustify (to have a fixed version)
        if: steps.cache-uncrustify.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/uncrustify/uncrustify/archive/refs/tags/uncrustify-0.72.0.tar.gz
          tar xzvf uncrustify-0.72.0.tar.gz && cd uncrustify-uncrustify-0.72.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j$(nproc) -s
          mkdir ~/uncrustify
          cd build && cp uncrustify ~/uncrustify/
      - name: Run Uncrustify
        run: |
          ~/uncrustify/uncrustify -c ./uncrustify.cfg --no-backup --replace examples/*/*.c examples/*/*.h
          git diff
          git diff | diff - /dev/null &> /dev/null
